SeaLion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.views.generic.base import RedirectView

from SeaLion.settings import MEDIA_ROOT
from activity import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.display_activity),
    url(r'^activity/', include('activity.urls', namespace='activityApp')),
    url(r'^user/', include('user.urls', namespace='userApp')),
    url(r'^notice/', include('billboard.urls', namespace='billboardApp')),

    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),
    url(r'^favicon.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
]

activity/urls.py
# -*-coding:utf-8-*-
from django.views.generic import RedirectView

__author__ = 'Nirvana'

from django.conf.urls import url
from django.views.static import serve

from SeaLion.settings import MEDIA_ROOT
from activity import views
from activity.views import Activity_Rec

app_name = 'activityApp'

urlpatterns = [

    url(r'^$', views.display_activity, name='index'),
    url(r'^index/$', views.display_activity, name='index'),
    url(r'^search/$', views.search_activity, name='search'),
    url(r'^create/$', views.create_activity, name='apply'),
    url(r'^delete/(?P<aid>[0-9]+)/$', views.delete_activity, name='delete'),
    url(r'^detail/(?P<aid>[0-9]+)/$', Activity_Rec.as_view(), name='detail'),
    url(r'^update/(?P<aid>[0-9]+)/$', views.update_activity, name='update'),
    url(r'^join/(?P<aid>[0-9]+)/$', views.join_activity, name='join'),
    url(r'^sign_condition/(?P<aid>[0-9]+)/$', views.sign_condition, name='sign_condition'),
    url(r'^sign/$', Activity_Rec.as_view()),
    url(r'^guest/(?P<aid>[0-9]+)/(?P<gid>[0-9]+)/$', views.guest_condition, name='guest'),

]

billboard/urls.py
#-*-coding:utf-8-*- 
__author__ = 'Nirvana'
from django.conf.urls import url

from billboard import views

app_name = 'noticeApp'
urlpatterns = [
    url(r'^billboard/$', views.billboard_display, name='billboard'),
    url(r'^detail/(?P<nid>[0-9]+)/$', views.notice_detail, name='detail'),
    url(r'^insert/$', views.notice_insert, name='insert'),
    url(r'^delete/(?P<nid>[0-9]+)/$', views.billboard_delete, name='delete'),
    url(r'^update/(?P<nid>[0-9]+)/$', views.billboard_update, name='update'),
]

user/urls.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'

from django.conf.urls import url
from django.urls import re_path

from user import views

app_name = 'userApp'
urlpatterns = [
    url(r'^login/$', views.userlogin, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^forget/$', views.forget, name='forget'),
    url(r'^logout/$', views.userlogout, name='logout'),
    url(r'^created/$', views.created_activities, name='created'),
    url(r'^joined/$', views.joined_activities, name='joined'),
    url(r'^update//$', views.updateProfile, name='update'),
    url(r'^upload/$', views.upload_image, name='upload'),
    url(r'^avatar/$', views.avatar_upload, name='avatar'),
    re_path(r'^profile/$', views.userProfile, name='profile'),

]

activity/models.py
from django.db import models

# Create your models here.
from SeaLion import settings


class Activity(models.Model):
    """
    活动表
    """
    title = models.CharField(verbose_name="活动名称", max_length=100, db_index=True)
    address = models.CharField(verbose_name='活动地点', max_length=50)
    start_time = models.DateTimeField(verbose_name='开始时间')
    isActive = models.BooleanField(verbose_name="是否开始签到", default=False)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='创建者', related_name='activities_creator',
                                on_delete=models.CASCADE)
    guests = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='嘉宾', related_name='activities_guest',
                                    blank=True)
    signed_in_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='activities_signed_in',
                                             verbose_name='已签到嘉宾')
    c_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    desc = models.TextField(verbose_name='活动描述', max_length=50, blank=True)
    notice = models.TextField(verbose_name='活动公告', max_length=50, blank=True)

    class Meta:
        ordering = ['-c_time', ]
        verbose_name = 'Activity'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

activity/forms.py
from django import forms
from activity.models import Activity


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'address', 'start_time', 'desc', 'isActive']
        widgets = {
            'start_time': forms.TimeInput,
            'desc': forms.Textarea(attrs={'cols': 50, 'rows': 10}),  # 关键是这一行
        }
        help_texts = {
            'start_time': 'eg. 1900/01/01 00:00'
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'address', 'start_time', 'desc', 'notice']
        widgets = {
            'desc': forms.Textarea(attrs={'cols': 50, 'rows': 10}),
            'notice': forms.Textarea(attrs={'cols': 50, 'rows': 10}),
        }

activity/views.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'

import base64
import os

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import View

from SeaLion import settings
from activity.forms import ActivityForm, UpdateForm
from activity.models import Activity
from user.models import PhotoModel
from billboard.models import Notice
from activity.utils import Pagintor

from datetime import datetime
import face_recognition as fr
import numpy as np

# Create your views here.

# 全局变量
known_face_encodings = []   # 活动嘉宾面部图像缓存列表
know_std_num= []            # 活动嘉宾学号缓存列表
msg = ''                    # 签到结果
result = ''                 # 签到人员信息


# 登陆限制装饰器类
class LoginRequiredMixin(object):
 @classmethod
 def as_view(cls, **initkwargs):
    view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
    return login_required(view)

def display_activity(request):
    """
    分页展示活动
    :param request: GET
    :return: 活动列表
    """
    if request.method == 'GET':
        ac_list = Activity.objects.all()
        Billboard = Notice.objects.all()[:3]
        apply_form = ActivityForm()                 # 给一个 创建活动 的空白表单
        activities_list = Pagintor(request=request, ac_list=ac_list, acount=4)
        if request.user.is_authenticated:
            if request.session.get('uploaded') is None:
                image_code = PhotoModel.objects.filter(user=request.user)
                if len(image_code) > 0:
                    # 如果用户照片不为空
                    request.session['uploaded'] = True
                else:
                    request.session['nav_msg'] = True
            message = request.session.get('message')    # 获取其他操作的提示信息
            if 'message' in request.session:
                del request.session['message']
    return render(request, 'activity/index.html', locals())


def search_activity(request):
    """
    活动查找
    :param request: GET
    :return: 查询结果列表
    """
    if request.method == 'GET':
        activity_msg = request.GET.get("activity_msg", "")
        activities_list = Activity.objects.all()
        apply_form = ActivityForm()
        if len(activity_msg) > 0:
            # 如果查询信息不为空
            activities_list = Activity.objects.filter(Q(title__contains=activity_msg) |
                                                      Q(address__contains=activity_msg) |
                                                      Q(creator__username__contains=activity_msg) |
                                                      Q(creator__nick_name__contains=activity_msg))
        activities_list = Pagintor(request=request, ac_list=activities_list, acount=4)
        Billboard = Notice.objects.all()[:3]
    return render(request, "activity/index.html", locals())


class Activity_Rec(LoginRequiredMixin, View):
    """
    活动签到功能控制类
    """
    def get(self,request,aid):
        """
        获取活动详情 如果request user是活动创建者 则获取该活动嘉宾列表
        :param request: 请求信息 GET
        :param aid: 活动id
        :return: 活动详情页面
        """
        global  known_face_encodings
        global  know_std_num
        activity= get_object_or_404(Activity, id=aid)
        update_form = UpdateForm(instance=activity)
        message = request.session.get('message')
        if 'message' in request.session:
            del request.session['message']
        if 'joined' in request.session:
            del request.session['joined']
        guests = activity.guests.all()
        if request.user == activity.creator:
            for gue in guests:
                gue_files = PhotoModel.objects.filter(user=gue)
                for file in gue_files:
                    img_code = np.load(file.img_code + '.npy')
                    known_face_encodings.append(img_code)
                    know_std_num.append(gue.std_num)
        sum_guest = guests.count()                          # 总人数
        signed_guest_list = activity.signed_in_users.all()  # 已签到嘉宾列表
        signed_guest_count = 0                              # 签到人数
        unsigned_guest_count = 0                            # 未签到人数
        sign_rate = 0.00                                    # 签到率
        if request.user in guests:
            # 如果请求者在嘉宾列表中，保存状态
            joined = True
            request.session['joined'] = joined
        if sum_guest > 0:
            signed_guest_count = signed_guest_list.count()
            unsigned_guest_count = sum_guest - signed_guest_count
            sign_rate = round((signed_guest_list.count() / sum_guest) * 100, 2)
        return render(request, "activity/detail.html", locals())

    def post(self,request):
        """
        获取前端发送的图像进行比对并返回结果
        :param request: 请求信息 POST
        :return: 识别结果
        """
        global known_face_encodings
        global know_std_num
        global msg
        global result
        unknown_face_tmp_encoding = []
        msg = 'failed'
        # 获取base64格式的图片
        aid = request.POST.get('aid')
        activity = get_object_or_404(Activity, id=aid)
        faceImage = request.POST.get('faceImg')
        # 提取出base64格式，并进行转换为图片
        index = faceImage.find('base64,')
        base64Str = faceImage[index + 6:]
        bytes_img = base64.b64decode(base64Str)
        # 将文件保存
        backupDate = datetime.now().strftime("%Y%m%d_%H%M%S")
        fileName = "Img_%s.jpg" % (backupDate)
        file_path = os.path.join("media", "image_cache",str(activity.title)+'_'+str(activity.id))   # 文件保存路径
        if not os.path.exists(file_path):
            # 不存在则创建
            os.mkdir(file_path)
        _file = os.path.join(file_path,fileName)
        file = open(_file, 'wb')
        file.write(bytes_img)
        file.close()
        # 删除多余的图片
        files = os.listdir(file_path)
        files.sort()
        ImgCount = files.__len__()
        try:
            if ImgCount > 10:
                # 图片超过100个，删除一个
                del_path = os.path.join(file_path, files[0])
                os.remove(del_path)
        except BaseException:
            pass
        try:
            unknown_face = fr.load_image_file(_file)
            unknown_face_tmp_encoding = fr.face_encodings(unknown_face)
        except BaseException:
            msg = 'failed'  # 图片中未发现人脸


        # 对图片进行人脸识别比对
        for face_encoding in unknown_face_tmp_encoding:
            matches = fr.compare_faces(known_face_encodings, face_encoding, 0.47)
            face_distances = fr.face_distance(known_face_encodings, face_encoding)
            try:
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    match = know_std_num[int(best_match_index)]
                    result = activity.guests.get(std_num=match)
                    msg = 'ok'
                    if result in activity.signed_in_users.all():
                        pass
                    else:
                        activity.signed_in_users.add(result)
                        activity.save()
            except:
                msg = 'failed'
        print(msg)
        return JsonResponse({'guest':str(result),'msg': msg})


@login_required(login_url=settings.LOGIN_URL)
def create_activity(request):
    """
    创建活动
    :param request:POST
    :return: 活动列表
    """
    if request.method == "POST":
        activity_form = ActivityForm(request.POST)
        message = '请检查填写内容！'
        if activity_form.is_valid():
            new_activity = activity_form.save(commit=False)
            try:
                new_activity.creator = request.user
                new_activity.save()
                message = '活动创建成功'
            except:
                message = '创建活动失败，请重试'
        request.session['message'] = message
    return HttpResponseRedirect(reverse('activityApp:index',))


@login_required(login_url=settings.LOGIN_URL)
def delete_activity(request, aid):
    """
    删除活动
    :param request: POST
    :param aid: 活动id
    :return:
    """
    activity = get_object_or_404(Activity, id=aid)
    try:
        activity.delete()
        message = '删除活动成功'
    except BaseException:
        message = '删除失败，请重试'
    request.session['message'] = message
    return HttpResponseRedirect(reverse('activityApp:index',))


@login_required(login_url=settings.LOGIN_URL)
def update_activity(request, aid):
    """
    修改活动信息
    :param request:  POST
    :param aid: 活动id
    :return:
    """
    activity = get_object_or_404(Activity, id=aid)
    update_form = UpdateForm(instance=activity, data=request.POST)
    if update_form.is_valid():
        update_form.save(commit=False)
        try:
            update_form.save()
            message = '修改成功'
        except BaseException:
            message = '修改失败，请重试'
        request.session['message'] = message
    return HttpResponseRedirect(reverse('activityApp:detail', args=(aid,)))


@login_required(login_url=settings.LOGIN_URL)
def sign_condition(request, aid):
    """
    活动签到状态更改（活动创建者）
    :param request: GET
    :param aid: activity id
    :return:
    """
    if request.method == "GET":
        activity = get_object_or_404(Activity, id=aid)
        try:
            activity.isActive = not activity.isActive
            activity.save()
            message = '操作成功'
        except:
            message = '操作失败'
        request.session['message'] = message
    return HttpResponseRedirect(reverse('activityApp:detail', args=(aid,)))


@login_required(login_url=settings.LOGIN_URL)
def join_activity(request, aid):
    """
    加入活动/退出活动
    :param request: GET
    :param aid: 活动id
    :return:
    """
    nav_msg = request.session.get('nav_msg')
    if not nav_msg:
        activity = get_object_or_404(Activity, id=aid)
        if not activity.isActive:
            joined = request.session.get('joined')
            if joined is  None:
                try:
                    activity.guests.add(request.user)

templates/activity/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}{{ activity.title }}{% endblock %}
{% block css %}<link href="{% static 'css/activity_detail.css' %}" rel="stylesheet"/>{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Entries Column -->
            <div class="col-md-8">
                <h1 class="page-header">
                    {{ activity.title }}
                    <small>活动详情</small>
                    <hr>
                    {% if message %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h5>{{ message }}</h5>
                        </div>
                    {% endif %}
                    {% if request.session.nav_msg %}
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h5>您没有上传个人照片不能加入任何活动，请尽快到<a href="{% url 'userApp:profile' %}" class="alert-link">个人中心</a>完善个人资料</h5>
                        </div>
                    {% endif %}
                </h1>
                <h2>
                    {% if activity.isActive %}
                        <small>活动不可加入</small>
                    {% else %}
                        <small>活动未开始</small>
                    {% endif %}

                    {% if activity.creator == request.user %}
                        {% if activity.isActive %}
                            <a class="btn btn-success"  href="{% url 'activityApp:sign_condition' activity.id %}">
                                开放活动<span class="glyphicon glyphicon glyphicon-off"></span></a>
                            {% if sum_guest > 0 %}
                                <a class="btn btn-primary" data-aid="{{ activity.id }}" id="signBtn" data-toggle="modal" data-target="#signModal">
                                    开始签到<span class="glyphicon glyphicon glyphicon-eye-open"></span></a>
{#                                <a class="btn btn-primary" href="{% url 'activityApp:sign' activity.id %}">#}
{#                                    开始签到<span class="glyphicon glyphicon glyphicon-eye-open"></span></a>#}
                            {% endif %}
                        {% else %}
                            <a class="btn btn-warning"  href="{% url 'activityApp:sign_condition' activity.id %}">
                                关闭活动<span class="glyphicon glyphicon glyphicon-off"></span></a>
                            <a class="btn btn-primary"  data-toggle="modal" data-target="#updateModal">修改活动信息 <span class="glyphicon glyphicon glyphicon-cog"></span></a>
                            <a class="btn btn-danger"  data-toggle="modal" data-target="#deleteModal">删除活动 <span class="glyphicon glyphicon glyphicon-trash"></span></a>
                        {% endif %}
                        <br>
                    {% else %}
                        {% if not activity.isActive %}
                            {% if not request.user in signed_guest_list %}
                             {% if joined %}
                                <a class="btn btn-danger" href="{% url 'activityApp:join' activity.id %}">退出活动 <span class="glyphicon glyphicon glyphicon-check"></span></a>
                            {% else %}
                                <a class="btn btn-primary" href="{% url 'activityApp:join' activity.id %}">加入活动 <span class="glyphicon glyphicon-chevron-right"></span></a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    {% endif %}
                </h2>

                <p><span class="glyphicon glyphicon-time"></span> {{ activity.start_time }}</p>
                <p><span class="glyphicon glyphicon-map-marker"></span> {{ activity.address }}</p>
                {% if activity.desc %}
                    <p><span class="glyphicon glyphicon-tag"></span> {{ activity.desc }}</p>
                {% else %}
                    <p><span class="glyphicon glyphicon-tag"></span> 无活动简述</p>
                {% endif %}

                <br>
                <h2><small>嘉宾名单</small></h2>
                {% if guests %}
                    {% for guest in guests %}
                        <div class="col-sm-2 col-md-2">
                             <div title= 学号：{{ guest.std_num }}>
                                <a href="{% url 'activityApp:guest' activity.id guest.id %}">
                                    {% if guest in signed_guest_list %}
                                    <img class="thumbnail guest-avatar" src="{{guest.profile.avatar.url}}" alt="用户头像">
                                    {% else %}
                                    <img class="thumbnail guest-avatar" src="/media/avatar/default.png" alt="默认头像">
                                    {% endif %}
                                </a>
                             </div>
                            <p style="margin-top: 10px;margin-left: 10px"><span class="glyphicon glyphicon-user"></span> {{ guest.username }}</p>
                        </div>
                {% endfor %}
                {% else %}
                    <p>空</p>
                {% endif %}

            </div>

            <!--Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Creator Profile Well -->
                <div class="panel panel-primary hidden-xs">
                    <div class="panel-heading">活动创建者</div>
                      <div class="panel-body">
                          <div class="col-sm-4 col-md-4">
                                 <img class="thumbnail guest-avatar" src="{{ activity.creator.profile.avatar.url }}"  alt="img loading...">
                         </div>
                          <p><span class="glyphicon glyphicon-user"></span> {{ activity.creator }}</p>
                      </div>
                </div>

                <!-- Blog Search Well -->
                <div class="panel panel-success">
                    <div class="panel-heading">签到情况统计</div>
                  <div class="panel-body">
                    <h4>签到情况统计</h4>
                      共{{ sum_guest }}位嘉宾<br>已签到{{ signed_guest_count }}人，未签到{{ unsigned_guest_count }}人<br>
                      {% if sum_guest != 0 and activity.isActive %}
                            签到率 {{ sign_rate }} %<br>
                      {% endif %}
                  </div>
                </div>

                <!-- Side Widget Well -->
                <div class="panel panel-info">
                    <div class="panel-heading">公告栏</div>
                  <div class="panel-body">
                      {% if activity.notice %}
                          <p>{{ activity.notice }}</p>
                          {% else %}
                          <p>创建者还未发布任何公告</p>
                      {% endif %}
                  </div>
                </div>


            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

     <!-- update Activity Modal -->
    <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">修改活动信息</h4>
          </div>
          <div class="modal-body">
            <form class="form" action="{% url 'activityApp:update' activity.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form update_form %}
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit"  class="btn btn-primary">确定</button>
                  </div>
            </form>
          </div>
        </div>
      </div>
    </div><!-- /.update Activity Modal -->
    <!-- delete Activity Modal -->
    <div class="modal fade bs-example-modal-sm" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>确认删除该活动吗？</h4>
            </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
              <a class="btn btn-danger" href="{% url 'activityApp:delete' activity.id %}">确定</a>
          </div>
        </div>
      </div>
    </div><!-- /.update Activity Modal -->

     <div class="modal fade bs-example-modal-sm" id="signModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="container">
            <video width="640" height="480" id="video" preload autoplay loop muted style="position: absolute"></video>
            <canvas width="640" height="480" id="canvas" style="position: absolute"></canvas>
          </div>
            <div class="container">
                <div class="label camera-msg-label label-success show-sign-status"></div>
                <div class="label camera-msg-label label-danger show-error-status"></div>
            </div>
        </div>
        <div class="modal-footer col-lg-offset-1">
          <button type="button" class="btn btn-default" data-dismiss="modal" style="position: absolute">关闭</button>
        </div>
      </div>
    </div><!-- /.sign Activity Modal -->

{% endblock %}
{% block js %}

    <script type="text/javascript" src="{% static 'js/tracking/tracking-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tracking/face-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myJS.js' %}"></script>
    <script type="text/javascript">
        // 获取摄像头 人脸捕捉
        $('#signBtn').click(function () {
            //激活摄像头
            navigator.getUserMedia  = navigator.getUserMedia ||
              navigator.webkitGetUserMedia ||
              navigator.mozGetUserMedia ||
              navigator.msGetUserMedia;
            navigator.getUserMedia({video:true}, gotStream, noStream);

            function gotStream(stream) {
              video.srcObject = stream;
              video.onerror = function () {
                stream.stop();
              };
              stream.onended = noStream;
              video.onloadedmetadata = function () {
                alert('摄像头成功打开！');
              };
            }
            function noStream(err)
            {
              alert(err);
            }
              var aid = $(this).data('aid');
              var canvas = document.getElementById('canvas');
              var context = canvas.getContext('2d');
              var tracker = new tracking.ObjectTracker(['face']);
                 tracker.setInitialScale(4);
                 tracker.setStepSize(2);
                 tracker.setEdgesDensity(0.1);
                 tracker.on('track', function(event) {
                    context.clearRect(0, 0, canvas.width, canvas.height);
                    if (event.data.length > 0){
                        //如果画面中有人脸
                         context.drawImage(video, 0, 0, canvas.width, canvas.height);
                         event.data.forEach(function(rect) {
                            //在图中画框框
                             context.strokeStyle = '#019999';
                             context.lineWidth = 7;
                             context.strokeRect(rect.x, rect.y, rect.width, rect.height);
                             context.font = '20px Helvetica';
                             context.fillStyle = "#fff";
                             context.fillText('Hello!' , rect.x + rect.width + 5, rect.y + 11);
                           });
                         //上传画面数据
                        var snapData = canvas.toDataURL('image/jpeg');
                        uploadImage(snapData, aid)
                    }
              });
              tracking.track('#video', tracker, { camera: true });
        });

        // 图片上传方法
        function uploadImage(faceImg, aid) {
            $.ajax({
                type: "POST",
                url: "/activity/sign/",
                beforeSend: function (xhr, setting) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                dataType: 'json',
                data: {
                    "faceImg": faceImg,
                    'aid': aid,
                },
                success: function (data) {
                    // 返回成功
                    if(data.msg === 'ok'){
                        $('div.show-error-status').html( '');
                        $('div.show-sign-status').html(data.guest + ' 签到成功' );
                    }
                    if(data.msg === 'failed'){
                        $('div.show-error-status').html( '签到失败：未知用户');
                    }
                },
                error: function (data) {
                    // 返回失败
                    $('div.show-error-status').html('验证失败');
                },
            });
        }
    </script>
{% endblock %}