SeaLion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.views.generic.base import RedirectView

from SeaLion.settings import MEDIA_ROOT
from activity import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.display_activity),
    url(r'^activity/', include('activity.urls', namespace='activityApp')),
    url(r'^user/', include('user.urls', namespace='userApp')),
    url(r'^notice/', include('billboard.urls', namespace='billboardApp')),

    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),
    url(r'^favicon.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
]

billboard/urls.py
#-*-coding:utf-8-*- 
__author__ = 'Nirvana'
from django.conf.urls import url

from billboard import views

app_name = 'noticeApp'
urlpatterns = [
    url(r'^billboard/$', views.billboard_display, name='billboard'),
    url(r'^detail/(?P<nid>[0-9]+)/$', views.notice_detail, name='detail'),
    url(r'^insert/$', views.notice_insert, name='insert'),
    url(r'^delete/(?P<nid>[0-9]+)/$', views.billboard_delete, name='delete'),
    url(r'^update/(?P<nid>[0-9]+)/$', views.billboard_update, name='update'),
]

user/urls.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'

from django.conf.urls import url
from django.urls import re_path

from user import views

app_name = 'userApp'
urlpatterns = [
    url(r'^login/$', views.userlogin, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^forget/$', views.forget, name='forget'),
    url(r'^logout/$', views.userlogout, name='logout'),
    url(r'^created/$', views.created_activities, name='created'),
    url(r'^joined/$', views.joined_activities, name='joined'),
    url(r'^update//$', views.updateProfile, name='update'),
    url(r'^upload/$', views.upload_image, name='upload'),
    url(r'^avatar/$', views.avatar_upload, name='avatar'),
    re_path(r'^profile/$', views.userProfile, name='profile'),

]

billboard/models.py
from django.db import models
from SeaLion import settings
# Create your models here.
class Notice(models.Model):
    """
    公告表
    """
    announcer = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='创建者', related_name='notice_creator',
                                on_delete=models.CASCADE, blank=True)
    title = models.CharField(verbose_name='公告标题', max_length=50, blank=True)
    content = models.TextField(verbose_name='公告内容', blank=True)
    c_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __unicode__(self):
        return u'%s' % self.title

    class Meta:
        ordering = ['-c_time']
        verbose_name = 'Billboard'
        verbose_name_plural = verbose_name

billboard/forms.py
#-*-coding:utf-8-*- 
__author__ = 'Nirvana'
from django import forms
from billboard.models import Notice


class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'content']

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'content']

billboard/views.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from activity.utils import Pagintor
from billboard.models import Notice
from billboard.forms import UpdateForm,NoticeForm

from SeaLion import settings

# Create your views here.
def billboard_display(request):
    """
    展示活动公告列表
    :param request: GET
    :return: 公告列表
    """
    if request.method == 'GET':
        notices = Notice.objects.all()
        insert_form = NoticeForm()
        Billboard = Pagintor(request=request, ac_list=notices, acount=10)
        notice_insert_message = request.session.get('notice_insert_message')
        if 'notice_insert_message' in request.session:
            del request.session['notice_insert_message']
        message = request.session.get('message')
        if 'message' in request.session:
            del request.session['message']
    return render(request, 'notice/billboard.html', locals())


def notice_detail(request, nid):
    """
    公告详情
    :param request: GET
    :param nid: 公告id
    :return: 公告详情页面
    """
    if request.method == 'GET':
        notice = get_object_or_404(Notice,id=nid)
        update_form = UpdateForm(instance=notice)
        notice_update_message = request.session.get('notice_update_message')
        if 'notice_update_message' in request.session:
            del request.session['notice_update_message']
    return render(request, "notice/detail.html", locals())


@login_required(login_url=settings.LOGIN_URL)
def notice_insert(request):
    """
    创建公告
    :param request: POST
    :return: 公告列表
    """
    if request.method == "POST":
        insert_form = NoticeForm(request.POST)
        message = '请检查填写内容！'
        if insert_form.is_valid():
            new_notice = insert_form.save(commit=False)
            try:
                new_notice.announcer = request.user
                new_notice.save()
                message = '公告发布成功'
            except:
                message = '公告发布失败，请重试'
        request.session['notice_insert_message'] = message
    return HttpResponseRedirect(reverse('noticeApp:billboard',))

@login_required(login_url=settings.LOGIN_URL)
def billboard_delete(request, nid):
    """
    删除公告
    :param request: POST
    :param nid: 公告id
    :return: 公告列表
    """
    notice = get_object_or_404(Notice, id=nid)
    try:
        notice.delete()
        message = '删除公告成功'
    except BaseException:
        message = '删除失败，请重试'
    request.session['message'] = message
    return HttpResponseRedirect(reverse('noticeApp:billboard',))


def billboard_update(request, nid):
    """
    更改公告
    :param request: POST
    :param nid: 公告id
    :return: 公告详情
    """
    notice = get_object_or_404(Notice, id=nid)
    update_form = UpdateForm(instance=notice, data=request.POST)
    if update_form.is_valid():
        update_form.save(commit=False)
        try:
            update_form.save()
            message = '修改成功'
        except:
            message = '修改失败，请重试'
        request.session['notice_update_message'] = message
    return HttpResponseRedirect(reverse('noticeApp:detail', args=(nid,)))

templates/notice/billboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}Sea Lion - 公告{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container">

        <h1 class="page-header">
            公告栏
            <small>Billboard</small>
            {% if request.user.is_staff %}
                <a class="btn btn-primary"  data-toggle="modal" data-target="#insertModal">发布公告 <span class="glyphicon glyphicon glyphicon-edit"></span></a>
             {% endif %}
            <br>
            {% if notice_insert_message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5>{{ notice_insert_message }}</h5>
                </div>
            {% endif %}
            {% if request.user.is_authenticated %}
                {% if request.session.nav_msg %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h5>您没有上传个人照片不能加入任何活动，请尽快到<a href="{% url 'userApp:profile' %}" class="alert-link">个人中心</a>完善个人资料</h5>
                    </div>
                {% endif %}
            {% endif %}
        </h1>

        <div class="row">
          <table class="table table-hover" style="margin-left: 10px">
            <tbody>
              {% for notice in Billboard %}
                  <tr>
                    <td style="font-size: medium"><a href="{% url 'noticeApp:detail' notice.id %}" target="_blank">{{ notice.title }}</a></td>
                    <td><span class="glyphicon glyphicon-time"></span> {{ notice.c_time }}</td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

    </div><!-- Billboard Well -->


    <div class="pager" >
      <span class="step-links">
        {% if Billboard.has_previous %}
          <li class="previous"><a href="?page={{ Billboard.previous_page_number }}"><span aria-hidden="true">&larr;</span>上一页</a>
        {% endif %}
          {% if Billboard.has_next %}
            <li class="next"><a href="?page={{ Billboard.next_page_number }}">下一页<span aria-hidden="true">&rarr;</span></a>
        {% endif %}
          <span class="current">
              {% if Billboard.number and Billboard.paginator.num_pages%}
                第 {{ Billboard.number }} 页，共 {{ Billboard.paginator.num_pages }} 页
              {% else %}
                第 1 页，共 1 页
              {% endif %}
          </span>
      </span>
    </div><!-- Pager -->

    <!-- /.container -->

     <!-- update notice Modal -->
    <div class="modal fade" id="insertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">发布公告</h4>
          </div>
          <div class="modal-body">
            <form class="form" action="{% url 'noticeApp:insert'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form insert_form %}
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit"  class="btn btn-primary">确定</button>
                  </div>
            </form>
          </div>
        </div>
      </div>
    </div><!-- /.update notice Modal -->

{% endblock %}

templates/notice/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}{{ notice.title }}{% endblock %}
{% block css %}<link href="{% static 'css/notice_detail.css' %}" rel="stylesheet"/>{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container">
        <!-- Entries Column -->
        <h1 class="text-center">
            {{ notice.title }}

            {% if request.user.is_staff %}
                <a class="btn btn-primary"  data-toggle="modal" data-target="#updateModal">修改公告 <span class="glyphicon glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-danger"  data-toggle="modal" data-target="#deleteModal">删除公告 <span class="glyphicon glyphicon glyphicon-trash"></span></a>
             {% endif %}

            <hr>
            {% if notice_update_message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5>{{ notice_update_message }}</h5>
                </div>
            {% endif %}
            {% if request.session.nav_msg %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5>您没有上传个人照片不能加入任何活动，请尽快到<a href="{% url 'userApp:profile' %}" class="alert-link">个人中心</a>完善个人资料</h5>
                </div>
            {% endif %}
        </h1>

        <div class="notice">
            <p class="para">{{ notice.content }}</p>
            <br><br><br>
            <p class="inscribe">{{ notice.c_time| date:"Y年m月d日" }}</p>
        </div>

    </div>
    <!-- /.container -->

     <!-- update notice Modal -->
    <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">修改公告</h4>
          </div>
          <div class="modal-body">
            <form class="form" action="{% url 'noticeApp:update' notice.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form update_form %}
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit"  class="btn btn-primary">确定</button>
                  </div>
            </form>
          </div>
        </div>
      </div>
    </div><!-- /.update notice Modal -->

    <!-- delete notice Modal -->
    <div class="modal fade bs-example-modal-sm" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h4>确认删除该公告吗？</h4>
            </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
              <a class="btn btn-danger" href="{% url 'noticeApp:delete' notice.id %}">确定</a>
          </div>
        </div>
      </div>
    </div><!-- /.update notice Modal -->



{% endblock %}