SeaLion/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.views.generic.base import RedirectView

from SeaLion.settings import MEDIA_ROOT
from activity import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.display_activity),
    url(r'^activity/', include('activity.urls', namespace='activityApp')),
    url(r'^user/', include('user.urls', namespace='userApp')),
    url(r'^notice/', include('billboard.urls', namespace='billboardApp')),

    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),
    url(r'^favicon.ico$',RedirectView.as_view(url=r'static/favicon.ico')),
]

activity/urls.py
# -*-coding:utf-8-*-
from django.views.generic import RedirectView

__author__ = 'Nirvana'

from django.conf.urls import url
from django.views.static import serve

from SeaLion.settings import MEDIA_ROOT
from activity import views
from activity.views import Activity_Rec

app_name = 'activityApp'

urlpatterns = [

    url(r'^$', views.display_activity, name='index'),
    url(r'^index/$', views.display_activity, name='index'),
    url(r'^search/$', views.search_activity, name='search'),
    url(r'^create/$', views.create_activity, name='apply'),
    url(r'^delete/(?P<aid>[0-9]+)/$', views.delete_activity, name='delete'),
    url(r'^detail/(?P<aid>[0-9]+)/$', Activity_Rec.as_view(), name='detail'),
    url(r'^update/(?P<aid>[0-9]+)/$', views.update_activity, name='update'),
    url(r'^join/(?P<aid>[0-9]+)/$', views.join_activity, name='join'),
    url(r'^sign_condition/(?P<aid>[0-9]+)/$', views.sign_condition, name='sign_condition'),
    url(r'^sign/$', Activity_Rec.as_view()),
    url(r'^guest/(?P<aid>[0-9]+)/(?P<gid>[0-9]+)/$', views.guest_condition, name='guest'),

]

user/urls.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'

from django.conf.urls import url
from django.urls import re_path

from user import views

app_name = 'userApp'
urlpatterns = [
    url(r'^login/$', views.userlogin, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^forget/$', views.forget, name='forget'),
    url(r'^logout/$', views.userlogout, name='logout'),
    url(r'^created/$', views.created_activities, name='created'),
    url(r'^joined/$', views.joined_activities, name='joined'),
    url(r'^update//$', views.updateProfile, name='update'),
    url(r'^upload/$', views.upload_image, name='upload'),
    url(r'^avatar/$', views.avatar_upload, name='avatar'),
    re_path(r'^profile/$', views.userProfile, name='profile'),

]

user/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser,User

from SeaLion import settings


def user_directory_path(instance, filename):
    """
    自定义用户头像保存路径
    :param instance: 用户实例
    :param filename: 文件名
    :return: 路径
    """
    ext = filename.split('.')[-1]
    formal = filename.split('.')
    if formal is not 'default':
        filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    else:
        filename = 'default.png'
    return os.path.join("avatar",str(instance.user.id), filename)


class UserModel(AbstractUser):
    """
    拓展用户模型
    """
    nick_name = models.CharField(max_length=25, verbose_name='昵称', blank=False, unique=True)
    std_num = models.CharField(max_length=12, verbose_name='学号', unique=True, blank=True)
    std_class = models.CharField(max_length=25, verbose_name='班级', blank=True)
    tel = models.CharField(max_length=255, verbose_name='手机号', blank=False)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    class Meta:
        ordering = ['-std_class']
        verbose_name = 'User Info'
        verbose_name_plural = verbose_name


class UserAvatar(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to=user_directory_path, verbose_name='用户头像',  default=os.path.join("avatar", "default.png"))

    class Meta:
        ordering = ['-user']
        verbose_name = 'User Avatar'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{}'s avatar".format(self.user.username)


class PhotoModel(models.Model):
    """
    用户照片编码模型
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='用户', related_name='user', on_delete=models.CASCADE)
    user_img = models.ImageField(upload_to='user_photos', verbose_name='用户照片', blank=True)
    img_code = models.CharField(max_length=255, verbose_name='图像编码', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ["id"]
        verbose_name = "User Image Code File"
        verbose_name_plural = verbose_name

user/forms.py
# -*-coding:utf-8-*-
__author__ = 'Nirvana'
from django import forms
from django.utils.translation import ugettext_lazy as _
from user.models import UserModel, PhotoModel


class LoginForm(forms.Form):
    """
    用户登录表单
    """
    username = forms.CharField(label="账号", max_length=128, required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u"手机号/邮箱"}))
    password = forms.CharField(label="密码", max_length=256, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': u"密码"}))


class RegisterForm(forms.ModelForm):
    """
    用户注册表单
    """
    class Meta:
        model = UserModel
        fields = ['username', 'nick_name', 'tel', 'email', 'password', 'std_num', 'std_class']
        help_texts = {
            'nick_name': '150个字符或者更少，可包含字母，数字和仅有的@/./+/-/_符号',
            'username': '用户真实姓名',
            'email': '如xxx@163.com',
        }
        labels = {
            'email': _('电子邮箱'),
        }
        widgets = {
            'email': forms.EmailInput,
            'password':forms.PasswordInput()
        }

class ForgetForm(forms.Form):
    """
    更改密码信息提交表单
    """
    tel = forms.CharField(label="手机号码", max_length=256, required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u"申请账号使用的手机号码"}))
    email = forms.CharField(label="电子邮箱", max_length=256, required=True,
                               widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': u"申请账号使用的电子邮箱"}))
    new_password = forms.CharField(label="新的密码", max_length=256, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': u"密码"}))


class UpdateForm(forms.ModelForm):
    """
    用户信息表单
    """
    class Meta:
        model = UserModel
        fields = ['nick_name', 'username', 'std_num', 'std_class', 'email']
        help_texts = {
            'nick_name': '必填。150个字符或者更少。可包含字母，数字和仅有的@/./+/-/_符号。',
            'username': '必填。用户真实姓名。',
        }


class ImageForm(forms.ModelForm):
    """
    用户照片表单
    """
    class Meta:
        model = PhotoModel
        fields = ['user_img']


class AvatarUploadForm(forms.Form):
    avatar = forms.ImageField(label=" ", max_length=256, required=True)

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.decorators.cache import cache_control

import os
import hashlib
import face_recognition as fr
import numpy as np
from datetime import datetime

from SeaLion import settings
from activity.models import Activity
from activity.utils import Pagintor
from user import forms
from user.forms import ImageForm, AvatarUploadForm, UpdateForm, ForgetForm, LoginForm
from user.models import UserModel, PhotoModel, UserAvatar


# Create your views here.
def userlogin(request):
    """
    用户登录
    :param request:POST
    :return:登录成功返回主页  失败返回提示信息
    """
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            if '@' not in username:
                # 不是邮箱 则认为使用手机号登录
                username = hash_code(username)
            password = login_form.cleaned_data['password']
            password = hash_code(password)
            try:
                user = authenticate(username=username, password=password)
                if user and user.is_active:
                    login(request, user)
                    if 'error' in request.session:
                        # 删除之前缓存的登录失败提示信息
                        del request.session['login_error']
                    request.session['is_login'] = True
                    request.session['nick_name'] = user.nick_name
                    return HttpResponseRedirect(reverse('activityApp:index', ))
                login_error = '用户名密码错误'
            except:
                login_error = '用户不存在'
            request.session['login_error'] = login_error
            forget_form = ForgetForm()
        return render(request, 'login/login.html', locals())

    login_form = LoginForm()
    forget_form = ForgetForm()
    return render(request, 'login/login.html', locals())


def register(request):
    """
    用户注册
    :param request:POST
    :return: 注册成功返回登陆页面 注册失败返回提示信息
    """
    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        register_error = "请检查填写的内容！"
        if register_form.is_valid():
            nick_name = register_form.cleaned_data['nick_name']
            password = register_form.cleaned_data['password']
            tel = register_form.cleaned_data['tel']
            email = register_form.cleaned_data['email']
            username = register_form.cleaned_data['username']
            std_num = register_form.cleaned_data['std_num']
            std_class = register_form.cleaned_data['std_class']
            same_tel = UserModel.objects.filter(tel=tel)
            nick_name_only = UserModel.objects.filter(nick_name=nick_name)
            if same_tel:
                register_error = '该手机号已被注册，请使用别的手机号码！'
                return render(request, 'login/register.html', locals())
            if nick_name_only:
                register_error = '此昵称已存在！'
                return render(request, 'login/register.html', locals())
            new_user = UserModel()
            new_user.nick_name = nick_name
            new_user.username = username
            new_user.password = hash_code(password)
            new_user.tel = hash_code(tel)
            new_user.email = email
            new_user.std_num = std_num
            new_user.std_class = std_class
            new_user.save()
            avatar = UserAvatar(user=new_user)
            avatar.save()
            return redirect("userApp:login")
        else:
            return render(request, 'login/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())


def forget(request):
    """
    忘记密码
    :param request:
    :return:
    """
    if request.method == 'POST':
        forget_form = forms.ForgetForm(request.POST)
        if forget_form.is_valid():
            tel = forget_form.cleaned_data['tel']
            email = forget_form.cleaned_data['email']
            new_password = forget_form.cleaned_data['new_password']
            try:
                user = UserModel.objects.get(Q(tel=tel) | Q(email=email))
                if not user.is_staff:
                    user.password = hash_code(new_password)
                    user.save()
            except:
                request.session['login_error'] = "验证信息错误，请检查输入的手机号或电子邮箱是否正确"
    login_form = LoginForm()
    return render(request, 'login/login.html', locals())



def userlogout(request):
    """
    退出登录
    :param request:
    :return: 活动主页
    """
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('activityApp:index', ))
    request.session.flush()     # 清空缓存
    logout(request)
    return HttpResponseRedirect(reverse('activityApp:index', ))


@login_required(login_url=settings.LOGIN_URL)
@cache_control(must_revalidate=True, max_age=3600)
def userProfile(request):
    """
    个人主页
    :param request: GET
    :return: 个人主页页面
    """
    update_form = UpdateForm(instance=request.user)
    image_form = ImageForm()
    avatar_form = AvatarUploadForm()
    updateInfoMessage = request.session.get('updateInfoMessage')
    if 'updateInfoMessage' in request.session:
        del request.session['updateInfoMessage']
    return render(request, 'user/personal.html', locals())

@login_required(login_url=settings.LOGIN_URL)
def avatar_upload(request):
    """
    用户头像上传
    :param request:POST
    :return:
    """
    user = request.user
    user_profile = get_object_or_404(UserAvatar, user=user)

    if request.method == "POST":
        a_form = AvatarUploadForm(request.POST, request.FILES)
        if a_form.is_valid():
            current_avatar = user_profile.avatar
            if not current_avatar == os.path.join("avatar", "default.png"):
                current_avatar_path = os.path.join("media", "avatar" ,str(user.id), os.path.basename(current_avatar.url))
                os.remove(current_avatar_path)

            avatar = a_form.cleaned_data['avatar']
            user_profile.avatar = avatar # 将图片路径修改到当前数据库
            user_profile.save()
            return HttpResponseRedirect(reverse('userApp:profile'))

        request.session['updateInfoMessage'] = "头像上传失败"
    return HttpResponseRedirect(reverse('userApp:profile'))

@login_required(login_url=settings.LOGIN_URL)
def updateProfile(request):
    """
    修改个人信息
    :param request:POST
    :return:个人主页
    """
    if request.method == 'POST':
        updateInfoMessage = '修改信息已存在，请重试'
        user = request.user
        update_form = UpdateForm(instance=user, data=request.POST, files=request.FILES)
        if update_form.is_valid():
            update_form.save(commit=False)
            try:
                nick_name = update_form.cleaned_data['nick_name']
                std_num = update_form.cleaned_data['std_num']
                if not nick_name == user.nick_name:
                    nick_name_same = UserModel.objects.filter(nick_name=nick_name)
                    if nick_name_same:
                        updateInfoMessage = '修改信息已存在，无法更新'
                if not std_num == user.std_num:
                    std_num_same = UserModel.objects.filter(std_num=std_num)
                    if std_num_same:
                        updateInfoMessage = '修改信息已存在，无法更新'
                else:
                    updateInfoMessage = '保存成功'
                    update_form.save()
            except:
                updateInfoMessage = '保存失败请重试'

        request.session['updateInfoMessage'] = updateInfoMessage
    return HttpResponseRedirect(reverse('userApp:profile', ))


@login_required(login_url=settings.LOGIN_URL)
def upload_image(request):
    """
    照片上传处理
    :param request:POST
    :return: 个人主页
    """
    if request.method == 'POST':
        new_photo = PhotoModel(user=request.user)
        image_form = ImageForm(instance=new_photo, data=request.POST, files=request.FILES)
        if image_form.is_valid():
            image_form = image_form.save(commit=False)
            try:
                img_code = fr.face_encodings(
                    fr.load_image_file(image_form.user_img))    # 加载文件、编码
                save_path = os.path.join("media", "user_image_code", str(request.user.id))  # 文件保存路径
                if not os.path.exists(save_path):
                    # 不存在则创建
                    os.mkdir(save_path)
                file_path = os.path.join(save_path,datetime.now().strftime('%Y%m%d_%H%M%S'))
                np.save(file_path, img_code[0])
                image_form.user_img = None
                image_form.img_code = file_path
                image_form.save()
                request.session['uploaded'] = True
                if 'nav_msg' in request.session:
                    del request.session['nav_msg']
                return HttpResponseRedirect(reverse('userApp:profile'))
            except:
                request.session['updateInfoMessage'] = "照片上传失败"
        return HttpResponseRedirect(reverse('userApp:profile'))


@login_required(login_url=settings.LOGIN_URL)
@cache_control(must_revalidate=True, max_age=3600)
def created_activities(request):
    """
    获取我创建的所有活动的列表
    :param request:GET
    :return:
    """
    if request.method == 'GET':
        ac_list = Activity.objects.filter(creator=request.user)
        my_activities_list = Pagintor(request=request, ac_list=ac_list,acount=4)
        return render(request, 'user/myActivity.html', locals())
    return render(request, 'user/myActivity.html')


@login_required(login_url=settings.LOGIN_URL)

templates/user/joined.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}      <!-- 加载bootstrap3应用  -->
{% block title %}Sea Lion - 我加入的活动{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 10px">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked personal-nav">
              <li role="presentation"><a href="{% url 'userApp:profile' %}">个人资料</a></li>
              <li role="presentation"><a href="{% url 'userApp:created'%}">我创建的活动</a></li>
              <li role="presentation" class="active"><a href="{% url 'userApp:joined'%}">我加入的活动</a></li>
            </ul>
        </div>

        <div class="col-md-9 panel-content-custom">
                <h1 class="page-header">
                    我加入的活动
                    <br>
                    <small>The activities I joined</small>
                </h1>
                {% for activity in joined_activities_list %}
                    <div class="col-sm-6">
                        <h2>
                             {% if activity.title|length > 7 %}
                                <a href="{% url 'activityApp:detail' activity.id %}" target="_blank">{{ activity.title| truncatechars:7 }}...</a>
                                {% else %}
                                <a href="{% url 'activityApp:detail' activity.id %}" target="_blank">{{ activity.title }}</a>
                            {% endif %}
                            {% if activity.isActive %}
                                <small>正在签到</small>
                            {% else %}
                                <small>未开始签到</small>
                            {% endif %}
                        </h2>
                        <p><span class="glyphicon glyphicon-time"></span> {{ activity.start_time }}</p>
                        <p><span class="glyphicon glyphicon-user"></span> {{ activity.creator }}</p>
                        <p><span class="glyphicon glyphicon-map-marker"></span> {{ activity.address }}</p>
                        {% if activity.desc|length > 25 %}
                            <p><span class="glyphicon glyphicon-tag"></span> {{ activity.desc|default:"无" | truncatechars:25}}...</p>
                            {% else %}
                            <p><span class="glyphicon glyphicon-tag"></span> {{ activity.desc|default:"无"}}</p>
                        {% endif %}
                        <hr>
                    </div>
                {% endfor %}

                <!-- Pager -->
                <div class="col-md-12">
                    <div class="pager" >
                      <span class="step-links">
                        {% if joined_activities_list.has_previous %}
                          <li class="previous"><a href="?page={{ joined_activities_list.previous_page_number }}"><span aria-hidden="true">&larr;</span>上一页</a>
                        {% endif %}
                          {% if joined_activities_list.has_next %}
                            <li class="next"><a href="?page={{ joined_activities_list.next_page_number }}">下一页<span aria-hidden="true">&rarr;</span></a>
                        {% endif %}
                          <span class="current">
                              {% if activities_list.number and activities_list.paginator.num_pages%}
                                第 {{ activities_list.number }} 页，共 {{ activities_list.paginator.num_pages }} 页
                              {% else %}
                                第 1 页，共 1 页
                              {% endif %}
                          </span>
                      </span>
                    </div>
                </div>
            </div>

    </div> <!-- /container -->
{% endblock %}

templates/user/personal.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}      <!-- 加载bootstrap3应用  -->
{% load cache %}
{% block title %}Sea Lion - 个人主页{% endblock %}
{% block css %}
<link href="{% static 'css/personal.css' %}" rel="stylesheet">
{% endblock %}

{% cache 600 sidebar request.user.username %}
    {% block content %}

        <div class="container" style="margin-top: 10px" >

            <div class="col-md-2">
                <ul class="nav nav-pills nav-stacked">
                  <li role="presentation" class="active"><a href="{% url 'userApp:profile' %}">个人资料</a></li>
                  <li role="presentation" ><a href="{% url 'userApp:created'%}">我创建的活动</a></li>
                  <li role="presentation"><a href="{% url 'userApp:joined'%}">我加入的活动</a></li>
                </ul>
            </div>

            <div class="col-md-10">

                <div class="panel panel-default personal-panel">
                    <div class="panel-body">
                        <h3 style="margin-left: 30px">个人资料</h3>
                        {% if updateInfoMessage %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h5>{{ updateInfoMessage }}</h5>
                            </div>
                        {% endif %}
                        <hr>
                        <div class="panel-content">
                            <div class="col-lg-3">
                                <div class="content">
                                   <div class="row">
                                      <div id="avatar" class="col-md-12">
                                          <img class="img-circle avatar-view" src="{{ request.user.profile.avatar.url }}"  alt="Avatar">
                                          <div class="col-md-8 text-center " style="padding-top: 10px"><a role="button" data-toggle="modal" data-target="#avatarModal">修改头像</a></div>
                                      </div>
                                   </div>
                                </div>
                            </div>
                            <div class="col-lg-9">

                                <h4 style="padding: 10px;margin-left: 20px;font-size: medium">ID:  {{ request.user.nick_name }}</h4>

                                <hr>
                                <div class="col-md-12 ">
                                <div class="col-md-10"><h5 >昵称：{{ request.user.nick_name }}</h5></div>
                                <div class="col-md-2"><a role="button" data-toggle="modal" data-target="#userInfoModal" >修改资料</a></div>
                                </div>

                                <div class="col-md-12">
                                <div class="col-md-10"><h5>实名：{{ request.user.username }}</h5></div>
                                <br>
                                <div class="col-md-10"><h5>学号：{{ request.user.std_num }}</h5></div>
                                <br>
                                <div class="col-md-10"><h5>班级：{{ request.user.std_class }}</h5></div>
                                <br>
                            </div>

                                <div class="col-md-12">
                                    <div class="col-md-10">
                                        <h5>个人照片：
                                            {% if request.session.uploaded %}
                                                已上传
                                            {% else %}
                                                <a role="button" data-toggle="modal" data-target="#imgRecModal" >上传图片</a>
                                            {% endif %}
                                        </h5>
                                    </div>
                                    {% if request.session.uploaded %}
                                        <div class="col-md-2"><a role="button" data-toggle="modal" data-target="#imgRecModal" >重新上传</a></div>
                                    {% endif %}
                            </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="userInfoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">修改个人信息</h4>
                  </div>
                  <div class="modal-body">
                    <form class="form" action="{% url 'userApp:update' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form update_form %}
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                            <button type="submit"  class="btn btn-primary">保存</button>
                          </div>
                    </form>
                  </div>
                </div>
              </div>
            </div><!-- /userInfoModal -->

            <div class="modal fade" id="avatarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                     <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">上传头像</h4>
                      </div>
                  <div class="modal-body">
                    <form class="form" action="{% url 'userApp:avatar' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form avatar_form %}
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="submit" class="btn btn-primary">保存</button>
                          </div>
                    </form>
                  </div>
                </div>
              </div>
            </div><!-- /imgRecModal -->

            <div class="modal fade" id="imgRecModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                     <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">上传个人照片</h4>
                      </div>
                  <div class="modal-body">
                    <form class="form" action="{% url 'userApp:upload' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form image_form %}
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="submit" id="saveButton" data-loading-text="正在上传中..." class="btn btn-primary">保存</button>
                          </div>
                    </form>
                  </div>
                </div>
              </div>
            </div><!-- /imgRecModal -->

        </div>


    {% endblock %}

{% endcache %}

{% block js %}
    <script src="{% static 'cropper/cropper.min.js' %}"></script>
    <script src="{% static 'sitelogo/sitelogo.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myJS.js' %}"></script>
{% endblock %}